-
  name: Deploying web server on remote server deb9test
  hosts: TGBSquid
  tasks:
    - name: Installing apache testserver
      apt:
        name: apache2 state= latest

    - name: Start service apache2
      service:
        name: apache2
        state: started

    #- name: Mysql server Installation
    #  apt: name= '{{ item }}' state= installed
    #  with_items:
    #    - mysql-server
    #    - mysql-client

    - name: Start mysql server
      systemd:
        name: mysql
        state: started
        enabled: yes
